### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by keebot-png** [frnega/Recipe-app#7]
- [x] Link to project: https://github.com/users/frnega/projects/4
- [x] There are 2 coding partners in the project.

**Comment by BregornOriginal** [comment]
## Hi @Team 👏🏼 

## Good job so far!

## There are some issues that you still need to work on to go to the next project but you are almost there!

![one-step-closer-one-more](https://user-images.githubusercontent.com/93630700/224693029-c2a3c17a-00e4-44d4-9cc3-977a0f89954c.gif)

## Highlights

✅ Good work creating a kanban board as a team 💯 

## Required Changes ♻️
_Check the comments under the review._

- Kindly add a column for reviews called `in review`
- As we are creating cards for each requirement, kindly add the following cards for the next requirements missing on the kanban board

![image](https://user-images.githubusercontent.com/93630700/224692921-abf3667d-5c4a-4407-a865-f6496931d412.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @keebot-png and @frnega,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
